from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import CarViewSet

# Create a DefaultRouter instance for automatic URL routing
router = DefaultRouter()

# Register the CarViewSet with the router under the 'cars' path
router.register(r'cars', CarViewSet)

urlpatterns = [
    # Include all URLs generated by the DefaultRouter
    # This includes routes for handling CRUD operations on the 'cars' endpoint
    path('', include(router.urls)),
]
