from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import VehicleViewSet
from .views import BikeListCreateAPIView, BikeDetailAPIView, UserListAPIView

# Create a DefaultRouter instance for automatic URL routing
router = DefaultRouter()

# Register the VehicleViewSet with the router under the 'vehicles' path
router.register(r'vehicles', VehicleViewSet)

urlpatterns = [
    # Include the URLs generated by the DefaultRouter for the 'vehicles' endpoint
    path('', include(router.urls)),
    
    # Define a URL pattern for listing and creating bikes
    # It maps to the BikeListCreateAPIView view
    path('bikes/', BikeListCreateAPIView.as_view(), name='bike-list-create'),
    
    # Define a URL pattern for listing users
    # It maps to the UserListAPIView view
    path('users/', UserListAPIView.as_view(), name='user-list'),
    
    # Define a URL pattern for retrieving, updating, or deleting a specific bike
    # It maps to the BikeDetailAPIView view, using an integer 'pk' as a path parameter
    path('bikes/<int:pk>/', BikeDetailAPIView.as_view(), name='bike-detail'),
]
