# Generated by Django 5.0.7 on 2024-07-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('number_plate', models.CharField(max_length=255)),
                ('assigned_driver', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
